name: Check for non-ascii characters in tex documents
on: [pull_request]
jobs:
  non-ascii:
    name: Check for non-ascii characters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout action
        uses: actions/checkout@v2
      - name: "Checking for non-ascii characters. Presence of non-ascii characters will result in failure."
        shell: bash
        run: |
          counter=0
          for FILENAME in `find ./tex -name *.tex`
          do
            perl -ne '/[\x80-\xFF]/&&print($ARGV."($.):\t^".$_)' $FILENAME > non-ascii-chars.txt
            while read h
              do echo "$h"
              let "counter=counter+1"
            done < non-ascii-chars.txt
            rm non-ascii-chars.txt
          done
          echo "######################################################"
          echo "There are " $counter " non-ascii characters in ./tex/*.tex"
          echo "######################################################"
          exit $counter

